### ISSUE TITLE
Emails are being delivered via letter opener in test, cucumber environments

### ISSUE THREAD

**Issue by calebhearth** [ryanb/letter_opener#57]
For some reason, LetterOpener is kicking in during rspec and cucumber runs.

Unfortunately, we send out a lot of emails (user creation, friend requests, etc.) and the tabs opened via letter opener are numbering in the dozens to hundreds.

**Gemfile**

``` ruby
group :development do
  gem 'letter_opener', '1.0.0'
```

**config/environments/development.rb**

``` ruby
  config.action_mailer.delivery_method = :letter_opener
```

**config/environments/test.rb**

``` ruby
  config.action_mailer.delivery_method = :test
```

**config/environments/cucumber.rb**

``` ruby
  config.action_mailer.delivery_method = :test
```

No mention of letter_opener in **config/environment.rb**.

**Comment by jaryl** [comment]
Really old issue, but I just ran into this issue. In this case, the problem was that I had sidekiq set up on my machine, and when the tests were ran, they triggered jobs on sidekiq, which was running in development, hence the emails were sent out.

Do the following in your `environment/test.rb`:
```
config.active_job.queue_adapter = :inline
```

**Comment by seyonv** [comment]
I was having the same issue with letters being delivered that I think other may be facing. It's an easy to make (but big mistake) that people might be making. It leads to not only this letter opener problem but to data being saved in the wrong place

Its  using `rails s` along with a javascript driver that opens the browser like selenium

Yup. rails s will launch your **development server** by default. So when you run your specs, the database persisted to will be the development database and Rails will act as if its the development environment (because it is).

The fix is to use `$rails s -e test` when you want to use Selenium.

I am however, still facing this issue when using a headless browser like Poltergeist. Trying to fix at the moment.

**Comment by denwwer** [comment]
most efficient fix: In `rails_helper.rb` or `spec_helper.rb` depend on your config
```
class LetterOpener::DeliveryMethod
  def deliver!(mail); true; end
end
